// Generated by Wrangler on Sun Apr 07 2024 22:01:45 GMT-0300 (hora estándar de Argentina)
// by running `wrangler types`

export {};
declare global {
	const MY_KV: string;
	const DB: D1Database;
	const MY_RATE_LIMITER: any;
}
