// Generated by Wrangler on Sat Apr 06 2024 12:52:31 GMT-0300 (hora estándar de Argentina)
// by running `wrangler types`

export {};
declare global {
	const MY_KV: string;
	const DB: D1Database;
	const MY_RATE_LIMITER: any;
}
